"""Domain models for the DeepResearch pipeline.

All models are Pydantic v2 models for validation and serialization.
Timestamps use injectable clock via default_factory.
"""

from __future__ import annotations

from datetime import UTC, datetime
from enum import StrEnum
from typing import Literal
from urllib.parse import urlparse

from pydantic import BaseModel, Field, field_validator, model_validator


def _utc_now() -> datetime:
    """Default clock — returns current UTC time. Overridable in tests."""
    return datetime.now(UTC)


class ResearchRequest(BaseModel):
    """Input to the deep_research tool."""

    query: str = Field(min_length=1, max_length=5000, description="Research query")
    depth: Literal["quick", "standard", "deep"] = "standard"
    max_sources: int = Field(default=8, ge=1, le=100)
    recency_days: int | None = Field(default=None, ge=1, le=3650)
    output_format: Literal["markdown"] = "markdown"

    @field_validator("query")
    @classmethod
    def _normalize_query(cls, v: str) -> str:
        v = v.strip()
        if not v:
            msg = "Query must not be empty or whitespace-only"
            raise ValueError(msg)
        # Remove dangerous control characters, keep normal whitespace
        return "".join(ch for ch in v if ch >= " " or ch in ("\n", "\t"))


class SearchQuery(BaseModel):
    """A single search query generated by the planner."""

    query: str = Field(min_length=1)
    variant: str = Field(default="exact", description="Query variant label")
    original_query: str = Field(min_length=1, description="Original user query")


class SearchResult(BaseModel):
    """A single result from a search provider."""

    title: str = ""
    url: str = Field(min_length=1)
    snippet: str = ""
    source_provider: str = ""
    rank: int = 0
    fetched_at: datetime | None = None

    @field_validator("url")
    @classmethod
    def _validate_url(cls, v: str) -> str:
        parsed = urlparse(v)
        if parsed.scheme not in ("http", "https"):
            msg = f"URL scheme must be http or https, got: {parsed.scheme}"
            raise ValueError(msg)
        if not parsed.hostname:
            msg = "URL must have a hostname"
            raise ValueError(msg)
        return v


class FetchedPage(BaseModel):
    """Result of fetching a URL."""

    url: str
    final_url: str = ""
    status_code: int = 0
    content_type: str = ""
    body: bytes = b""
    fetched_at: datetime = Field(default_factory=_utc_now)
    error: str | None = None

    @property
    def is_success(self) -> bool:
        return self.error is None and 200 <= self.status_code < 300


class ExtractedDocument(BaseModel):
    """Clean text extracted from a fetched page."""

    url: str
    title: str = ""
    text: str = ""
    paragraphs: list[str] = Field(default_factory=list)
    extraction_method: str = "html"
    extracted_at: datetime = Field(default_factory=_utc_now)


class EvidenceItem(BaseModel):
    """A single piece of evidence from a source."""

    source_id: int
    snippet: str = Field(min_length=1)
    query_relevance: float = Field(default=0.0, ge=0.0, le=1.0)


class RankedSource(BaseModel):
    """A source with relevance score."""

    document: ExtractedDocument
    score: float = Field(default=0.0, ge=0.0)
    score_breakdown: dict[str, float] = Field(default_factory=dict)
    source_id: int = 0


class ResearchFinding(BaseModel):
    """A single finding in the research report."""

    statement: str
    evidence_ids: list[int] = Field(default_factory=list)
    confidence: float = Field(default=0.5, ge=0.0, le=1.0)
    limitations: list[str] = Field(default_factory=list)


class Citation(BaseModel):
    """A citation reference in the report."""

    source_id: int = Field(ge=1)
    title: str = ""
    url: str = ""
    domain: str = ""


class ResearchReport(BaseModel):
    """Complete research report."""

    query: str
    depth: str = "standard"
    summary: str = ""
    findings: list[ResearchFinding] = Field(default_factory=list)
    citations: list[Citation] = Field(default_factory=list)
    limitations: list[str] = Field(default_factory=list)
    source_count: int = 0
    generated_at: datetime = Field(default_factory=_utc_now)
    research_duration_seconds: float = 0.0

    @model_validator(mode="after")
    def _validate_citations(self) -> ResearchReport:
        """Ensure all cited source_ids exist in citations list."""
        cited_ids: set[int] = set()
        for f in self.findings:
            cited_ids.update(f.evidence_ids)
        available_ids = {c.source_id for c in self.citations}
        missing = cited_ids - available_ids
        if missing:
            msg = f"Findings reference missing citation ids: {missing}"
            raise ValueError(msg)
        return self


# ---------------------------------------------------------------------------
# Async job models (Stage 26)
# ---------------------------------------------------------------------------


class JobStatus(StrEnum):
    """Status of a research job."""

    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    EXPIRED = "expired"


class ResearchJob(BaseModel):
    """A background research job."""

    job_id: str = Field(min_length=1, description="Unique job identifier")
    query: str = Field(min_length=1)
    depth: str = "standard"
    max_sources: int = 8
    recency_days: int | None = None
    status: JobStatus = JobStatus.PENDING
    created_at: datetime = Field(default_factory=_utc_now)
    started_at: datetime | None = None
    completed_at: datetime | None = None
    report_markdown: str | None = None
    error_message: str | None = None
    source_count: int = 0
    research_duration_seconds: float = 0.0

    @property
    def is_terminal(self) -> bool:
        """Whether the job has reached a terminal state."""
        return self.status in (JobStatus.COMPLETED, JobStatus.FAILED, JobStatus.EXPIRED)
